name: "Set up Wasp App Runner"
description: |
  Set up Wasp App Runner for use in GitHub Actions workflows

  **Note:** You must set up Node.js before using this action.

inputs:
  checkout-path:
    description: "Path where to checkout the Wasp App Runner repository"
    required: false
    default: ".wasp-app-runner"

runs:
  using: "composite"
  steps:
    - name: Checkout wasp-app-runner (current repo, use triggering commit)
      if: ${{ github.repository == github.action_repository }}
      uses: actions/checkout@v4
      with:
        repository: wasp-lang/runner-action
        path: ${{ inputs['checkout-path'] }}
        ref: ${{ github.sha }}

    - name: Checkout wasp-app-runner (external repo, use default branch)
      if: ${{ github.repository != github.action_repository }}
      uses: actions/checkout@v4
      with:
        repository: wasp-lang/runner-action
        path: ${{ inputs['checkout-path'] }}

    - name: Cache npm cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs['checkout-path'] }}/.npm-cache
        key: npm-wasp-app-runner-${{ runner.os }}-${{ hashFiles(format('{0}/package-lock.json', inputs['checkout-path'])) }}
        restore-keys: |
          npm-wasp-app-runner-${{ runner.os }}-

    - name: Install dependencies and Wasp App Runner
      shell: bash
      working-directory: ${{ inputs['checkout-path'] }}
      env:
        npm_config_cache: ${{ github.workspace }}/${{ inputs['checkout-path'] }}/.npm-cache
      run: |
        npm ci
        npm install -g "$(npm pack --silent)"

    - name: Cleanup
      shell: bash
      run: |
        rm -rf ${{ inputs['checkout-path'] }}
