name: "Set up Wasp App Runner"
description: "Set up Wasp App Runner for use in GitHub Actions workflows"

inputs:
  path:
    description: "Path where to checkout the Wasp App Runner repository"
    required: false
    default: ".wasp-app-runner"
  node-version:
    description: "Node.js version to use"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Checkout wasp-app-runner
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.path }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs['node-version'] }}

    - name: Cache npm cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}/.npm-cache
        key: npm-wasp-app-runner-${{ runner.os }}-${{ hashFiles(format('{0}/package-lock.json', inputs.path)) }}
        restore-keys: |
          npm-wasp-app-runner-${{ runner.os }}-

    - name: Install dependencies and Wasp App Runner
      shell: bash
      working-directory: ${{ inputs.path }}
      env:
        npm_config_cache: ${{ github.workspace }}/${{ inputs.path }}/.npm-cache
      run: |
        npm ci
        npm run install:global
