name: "Wasp App Runner"
description: "Set up Wasp App Runner for use in GitHub Actions workflows"
runs:
  using: "composite"
  steps:
    - name: Checkout wasp-app-runner
      uses: actions/checkout@v4
      with:
        path: ".wasp-app-runner"

    - name: Install dependencies and Wasp App Runner
      shell: bash
      working-directory: ./.wasp-app-runner/wasp-app-runner
      run: |
        npm ci
        npm run install:global
