name: Test Wasp App Runner Action
on:
  push:
    branches:
      - "**"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/checkout@v4

      - name: Create test file
        run: touch test-file.txt

      - uses: ./
        with:
          wasp-app-runner-ref: ${{ github.sha }}

      - name: Verify installation
        run: run-wasp-app --help

      - name: Verify that we didn't change the working directory
        run: test -f test-file.txt
